sudo: false

language: node_js

node_js:
  - 6

cache:
  directories:
    - node_modules

notifications:
  email: false

before_install:
  - npm install -g coveralls lerna
  - lerna run -- prune

install:
  - npm run bootstrap

script:
  - npm test

after_success:
  - npm run coverage
  - coveralls < ./coverage/lcov.info || true
